# Generated by Django 4.2.3 on 2023-10-12 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_folder_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='folder',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.folder'),
            preserve_default=False,
        ),
    ]
